


unique_emp = "SELECT 'EMPLOYER_CODE='||Fcc2(EMPLOYER_CODE)||' AND '||'FUND_CODE='||Fcc2(FUND_CODE)||' AND '||'SCHEME_NUMBER='||Fcc2(SCHEME_NUMBER) FROM STG_MPF_EMPLOYER GROUP BY EMPLOYER_CODE, FUND_CODE, SCHEME_NUMBER HAVING COUNT(1)>1"
    